# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6952b1aa6ae3b24b51efc78face9bab52a6c6458ff1f39dff71bd86e4c0c3726dcfbf7906e602db310fd5e44401d40cb4dbe69c1088a9983aed069417a651f05

test:
  secret_key_base: e9cf0bea739e13e9ad60b3442c2cb0e15c745b7af5e49d05d823ba5af435c3e2825f4307534dfafa6b07e30a77e63e47411d43d5cf02e7a76a6cf0d865f25b9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
